### ISSUE TITLE
Training FIFA

### ISSUE THREAD

**Issue by muhammad-ahmed-ghani** [hasibzunair/fifa-tryon#1]
Hi @hasibzunair, I wanted to know how to train it on **768x1024** images and if I used the other **SOTA** models than **VGG** then will it train better ?

**Comment by hasibzunair** [comment]
Hi @muhammad-ahmed-ghani, sorry I missed this. You can try recent backbones other than VGG, might work better. To train it on high res, simply change the input dimensions in the data loader and model inputs.

**Comment by muhammad-ahmed-ghani** [comment]
Thank you.
